/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Wed Jul 19 05:25:55 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTestDriver_h__
#define __mkTestDriver_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMultiplier.h"


/* Class declaration for the mkTestDriver module */
class MOD_mkTestDriver : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_doneread;
  MOD_Reg<tUInt8> INST_m_doneread_double_write_error;
  MOD_Reg<tUInt32> INST_m_in;
  MOD_Reg<tUInt8> INST_m_in_double_write_error;
  MOD_Reg<tUInt8> INST_m_inited;
  MOD_Reg<tUInt8> INST_m_inited_double_write_error;
  MOD_Reg<tUInt32> INST_m_out;
  MOD_Reg<tUInt8> INST_m_out_double_write_error;
  MOD_Counter<tUInt32> INST_m_outstanding;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index_double_write_error;
  MOD_Fifo<tUInt32> INST_pipeline_chunker_infifo;
  MOD_Fifo<tUInt32> INST_pipeline_chunker_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_chunker_pending;
  MOD_Reg<tUInt8> INST_pipeline_chunker_pending_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_counter;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_counter_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_stage_reg;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_stage_reg_double_write_error;
  MOD_Fifo<tUInt32> INST_pipeline_fir_infifo;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_0;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_1;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_2;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_3;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_4;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_5;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_6;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_7;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_8;
  MOD_Fifo<tUInt32> INST_pipeline_fir_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_0;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_0_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_1;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_1_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_2;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_2_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_3;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_3_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_4;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_4_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_5;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_5_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_6;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_6_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_7;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_7_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_fromMP_inFifo;
  MOD_Fifo<tUWide> INST_pipeline_fromMP_outFifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_0_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_0_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_0_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_0_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_0_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_0_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_0_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_1_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_1_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_1_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_1_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_1_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_1_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_1_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_2_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_2_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_2_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_2_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_2_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_2_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_2_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_3_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_3_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_3_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_3_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_3_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_3_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_3_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_4_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_4_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_4_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_4_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_4_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_4_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_4_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_5_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_5_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_5_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_5_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_5_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_5_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_5_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_6_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_6_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_6_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_6_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_6_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_6_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_6_rel;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_7_idle;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_7_img;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_7_infifo;
  MOD_Reg<tUInt8> INST_pipeline_fromMP_ptcs_7_iter;
  MOD_Fifo<tUInt64> INST_pipeline_fromMP_ptcs_7_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_7_phase;
  MOD_Reg<tUInt32> INST_pipeline_fromMP_ptcs_7_rel;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_counter;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_counter_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_stage_reg;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_stage_reg_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_outfifo;
  MOD_Fifo<tUInt32> INST_pipeline_overSampler_infifo;
  MOD_Fifo<tUWide> INST_pipeline_overSampler_outfifo;
  MOD_Reg<tUWide> INST_pipeline_overSampler_window;
  MOD_Fifo<tUWide> INST_pipeline_overlayer_infifo;
  MOD_Fifo<tUInt32> INST_pipeline_overlayer_outfifo;
  MOD_Reg<tUWide> INST_pipeline_overlayer_window;
  MOD_Fifo<tUWide> INST_pipeline_pitchAdjust_dphaseFifo;
  MOD_Fifo<tUWide> INST_pipeline_pitchAdjust_inFifo;
  MOD_Fifo<tUWide> INST_pipeline_pitchAdjust_magFifo;
  MOD_Fifo<tUWide> INST_pipeline_pitchAdjust_outFifo;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index_double_write_error;
  MOD_Fifo<tUInt32> INST_pipeline_splitter_infifo;
  MOD_Fifo<tUInt32> INST_pipeline_splitter_outfifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_0_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_0_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_0_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_0_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_0_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_0_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_0_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_1_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_1_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_1_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_1_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_1_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_1_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_1_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_2_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_2_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_2_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_2_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_2_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_2_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_2_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_3_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_3_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_3_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_3_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_3_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_3_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_3_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_4_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_4_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_4_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_4_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_4_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_4_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_4_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_5_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_5_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_5_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_5_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_5_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_5_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_5_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_6_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_6_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_6_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_6_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_6_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_6_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_6_rel;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_7_idle;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_7_img;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_7_infifo;
  MOD_Reg<tUInt8> INST_pipeline_toMP_ctps_7_iter;
  MOD_Fifo<tUInt64> INST_pipeline_toMP_ctps_7_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_7_phase;
  MOD_Reg<tUInt32> INST_pipeline_toMP_ctps_7_rel;
  MOD_Fifo<tUWide> INST_pipeline_toMP_inFifo;
  MOD_Fifo<tUWide> INST_pipeline_toMP_outFifo;
 
 /* Constructor */
 public:
  MOD_mkTestDriver(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_finish;
  tUInt8 DEF_CAN_FIRE_RL_finish;
  tUInt8 DEF_WILL_FIRE_RL_write;
  tUInt8 DEF_CAN_FIRE_RL_write;
  tUInt8 DEF_WILL_FIRE_RL_pad;
  tUInt8 DEF_CAN_FIRE_RL_pad;
  tUInt8 DEF_WILL_FIRE_RL_read;
  tUInt8 DEF_CAN_FIRE_RL_read;
  tUInt8 DEF_WILL_FIRE_RL_init;
  tUInt8 DEF_CAN_FIRE_RL_init;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_overlayer_to_splitter;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_overlayer_to_splitter;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_to_overlayer;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_to_overlayer;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_to_ifft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_to_ifft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_pitchAdjust_to_fromMP;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_pitchAdjust_to_fromMP;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_to_pitchAdjust;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_to_pitchAdjust;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_to_toMP;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_to_toMP;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_oversampler_to_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_oversampler_to_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_to_oversampler;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_to_oversampler;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_overlayer_shiftout;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_overlayer_shiftout;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_circular_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_circular_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_stage_count;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_stage_count;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_gets;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_gets;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_puts;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_puts;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_7_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_7_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_7_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_7_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_6_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_6_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_6_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_6_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_5_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_5_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_5_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_5_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_4_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_4_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_4_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_4_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_3_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_3_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_3_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_3_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_2_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_2_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_2_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_2_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_1_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_1_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_1_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_1_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_0_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_0_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fromMP_ptcs_0_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fromMP_ptcs_0_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_pitchAdjust_result_index_calculate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_pitchAdjust_result_index_calculate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_pitchAdjust_dphase_calculate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_pitchAdjust_dphase_calculate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_gets;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_gets;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_puts;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_puts;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_7_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_7_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_7_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_7_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_6_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_6_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_6_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_6_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_5_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_5_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_5_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_5_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_4_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_4_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_4_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_4_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_3_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_3_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_3_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_3_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_2_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_2_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_2_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_2_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_1_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_1_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_1_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_1_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_0_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_0_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_toMP_ctps_0_start;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_toMP_ctps_0_start;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_circular_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_circular_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_stage_count;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_stage_count;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_overSampler_shiftin;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_overSampler_shiftin;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_process1;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_process1;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_process0;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_process0;
  tUInt8 DEF_x__h231860;
  tUInt8 DEF_x__h14869;
  tUInt8 DEF_pipeline_chunker_index__h7548;
  tUInt64 DEF_pipeline_toMP_ctps_7_infifo_first____d1689;
  tUInt64 DEF_pipeline_toMP_ctps_6_infifo_first____d1576;
  tUInt64 DEF_pipeline_toMP_ctps_5_infifo_first____d1463;
  tUInt64 DEF_pipeline_toMP_ctps_4_infifo_first____d1350;
  tUInt64 DEF_pipeline_toMP_ctps_3_infifo_first____d1237;
  tUInt64 DEF_pipeline_toMP_ctps_2_infifo_first____d1124;
  tUInt64 DEF_pipeline_toMP_ctps_1_infifo_first____d1011;
  tUInt64 DEF_pipeline_toMP_ctps_0_infifo_first____d897;
  tUInt8 DEF_x__h224812;
  tUInt8 DEF_x__h219593;
  tUInt8 DEF_x__h214374;
  tUInt8 DEF_x__h209155;
  tUInt8 DEF_x__h203936;
  tUInt8 DEF_x__h198717;
  tUInt8 DEF_x__h193498;
  tUInt8 DEF_x__h188279;
  tUInt8 DEF_x__h169087;
  tUInt8 DEF_x__h163895;
  tUInt8 DEF_x__h158703;
  tUInt8 DEF_x__h153511;
  tUInt8 DEF_x__h148319;
  tUInt8 DEF_x__h143127;
  tUInt8 DEF_x__h137935;
  tUInt8 DEF_x__h132740;
  tUInt32 DEF_pipeline_toMP_ctps_7_infifo_first__689_BITS_63_ETC___d1711;
  tUInt32 DEF_pipeline_toMP_ctps_7_infifo_first__689_BITS_31_ETC___d1695;
  tUInt32 DEF_pipeline_toMP_ctps_6_infifo_first__576_BITS_63_ETC___d1598;
  tUInt32 DEF_pipeline_toMP_ctps_6_infifo_first__576_BITS_31_ETC___d1582;
  tUInt32 DEF_pipeline_toMP_ctps_5_infifo_first__463_BITS_63_ETC___d1485;
  tUInt32 DEF_pipeline_toMP_ctps_5_infifo_first__463_BITS_31_ETC___d1469;
  tUInt32 DEF_pipeline_toMP_ctps_4_infifo_first__350_BITS_63_ETC___d1372;
  tUInt32 DEF_pipeline_toMP_ctps_4_infifo_first__350_BITS_31_ETC___d1356;
  tUInt32 DEF_pipeline_toMP_ctps_3_infifo_first__237_BITS_63_ETC___d1259;
  tUInt32 DEF_pipeline_toMP_ctps_3_infifo_first__237_BITS_31_ETC___d1243;
  tUInt32 DEF_pipeline_toMP_ctps_2_infifo_first__124_BITS_63_ETC___d1146;
  tUInt32 DEF_pipeline_toMP_ctps_2_infifo_first__124_BITS_31_ETC___d1130;
  tUInt32 DEF_pipeline_toMP_ctps_1_infifo_first__011_BITS_63_ETC___d1033;
  tUInt32 DEF_pipeline_toMP_ctps_1_infifo_first__011_BITS_31_ETC___d1017;
  tUInt32 DEF_pipeline_toMP_ctps_0_infifo_first__97_BITS_63__ETC___d919;
  tUInt32 DEF_pipeline_toMP_ctps_0_infifo_first__97_BITS_31__ETC___d903;
  tUInt32 DEF_x_first_rel_i__h167927;
  tUInt32 DEF_x_first_rel_f__h167928;
  tUInt32 DEF_x_first_img_i__h167951;
  tUInt32 DEF_x_first_img_f__h167952;
  tUInt32 DEF_x_first_rel_i__h162735;
  tUInt32 DEF_x_first_rel_f__h162736;
  tUInt32 DEF_x_first_img_i__h162759;
  tUInt32 DEF_x_first_img_f__h162760;
  tUInt32 DEF_x_first_rel_i__h157543;
  tUInt32 DEF_x_first_rel_f__h157544;
  tUInt32 DEF_x_first_img_i__h157567;
  tUInt32 DEF_x_first_img_f__h157568;
  tUInt32 DEF_x_first_rel_i__h152351;
  tUInt32 DEF_x_first_rel_f__h152352;
  tUInt32 DEF_x_first_img_i__h152375;
  tUInt32 DEF_x_first_img_f__h152376;
  tUInt32 DEF_x_first_rel_i__h147159;
  tUInt32 DEF_x_first_rel_f__h147160;
  tUInt32 DEF_x_first_img_i__h147183;
  tUInt32 DEF_x_first_img_f__h147184;
  tUInt32 DEF_x_first_rel_i__h141967;
  tUInt32 DEF_x_first_rel_f__h141968;
  tUInt32 DEF_x_first_img_i__h141991;
  tUInt32 DEF_x_first_img_f__h141992;
  tUInt32 DEF_x_first_rel_i__h136775;
  tUInt32 DEF_x_first_rel_f__h136776;
  tUInt32 DEF_x_first_img_i__h136799;
  tUInt32 DEF_x_first_img_f__h136800;
  tUInt32 DEF_x_first_rel_i__h131505;
  tUInt32 DEF_x_first_rel_f__h131506;
  tUInt32 DEF_x_first_img_i__h131532;
  tUInt32 DEF_x_first_img_f__h131533;
  tUInt32 DEF_i___1_i__h168047;
  tUInt32 DEF_x__h168045;
  tUInt32 DEF_i___1_f__h168048;
  tUInt32 DEF_r___1_i__h168015;
  tUInt32 DEF_x__h168013;
  tUInt32 DEF_r___1_f__h168016;
  tUInt32 DEF_i___1_i__h162855;
  tUInt32 DEF_x__h162853;
  tUInt32 DEF_i___1_f__h162856;
  tUInt32 DEF_r___1_i__h162823;
  tUInt32 DEF_x__h162821;
  tUInt32 DEF_r___1_f__h162824;
  tUInt32 DEF_i___1_i__h157663;
  tUInt32 DEF_x__h157661;
  tUInt32 DEF_i___1_f__h157664;
  tUInt32 DEF_r___1_i__h157631;
  tUInt32 DEF_x__h157629;
  tUInt32 DEF_r___1_f__h157632;
  tUInt32 DEF_i___1_i__h152471;
  tUInt32 DEF_x__h152469;
  tUInt32 DEF_i___1_f__h152472;
  tUInt32 DEF_r___1_i__h152439;
  tUInt32 DEF_x__h152437;
  tUInt32 DEF_r___1_f__h152440;
  tUInt32 DEF_i___1_i__h147279;
  tUInt32 DEF_x__h147277;
  tUInt32 DEF_i___1_f__h147280;
  tUInt32 DEF_r___1_i__h147247;
  tUInt32 DEF_x__h147245;
  tUInt32 DEF_r___1_f__h147248;
  tUInt32 DEF_i___1_i__h142087;
  tUInt32 DEF_x__h142085;
  tUInt32 DEF_i___1_f__h142088;
  tUInt32 DEF_r___1_i__h142055;
  tUInt32 DEF_x__h142053;
  tUInt32 DEF_r___1_f__h142056;
  tUInt32 DEF_i___1_i__h136895;
  tUInt32 DEF_x__h136893;
  tUInt32 DEF_i___1_f__h136896;
  tUInt32 DEF_r___1_i__h136863;
  tUInt32 DEF_x__h136861;
  tUInt32 DEF_r___1_f__h136864;
  tUInt32 DEF_i___1_i__h131646;
  tUInt32 DEF_x__h131644;
  tUInt32 DEF_i___1_f__h131647;
  tUInt32 DEF_r___1_i__h131614;
  tUInt32 DEF_x__h131612;
  tUInt32 DEF_r___1_f__h131615;
  tUInt8 DEF_pipeline_toMP_ctps_7_infifo_first__689_BIT_63___d1690;
  tUInt8 DEF_pipeline_toMP_ctps_6_infifo_first__576_BIT_63___d1577;
  tUInt8 DEF_pipeline_toMP_ctps_5_infifo_first__463_BIT_63___d1464;
  tUInt8 DEF_pipeline_toMP_ctps_4_infifo_first__350_BIT_63___d1351;
  tUInt8 DEF_pipeline_toMP_ctps_3_infifo_first__237_BIT_63___d1238;
  tUInt8 DEF_pipeline_toMP_ctps_2_infifo_first__124_BIT_63___d1125;
  tUInt8 DEF_pipeline_toMP_ctps_1_infifo_first__011_BIT_63___d1012;
  tUInt8 DEF_pipeline_toMP_ctps_0_infifo_first__97_BIT_63___d898;
  tUInt8 DEF_pipeline_ifft_fft_fft_counter_633_EQ_0___d2637;
  tUInt8 DEF_pipeline_toMP_ctps_7_infifo_first__689_BIT_63__ETC___d1693;
  tUInt8 DEF_pipeline_toMP_ctps_6_infifo_first__576_BIT_63__ETC___d1580;
  tUInt8 DEF_pipeline_toMP_ctps_5_infifo_first__463_BIT_63__ETC___d1467;
  tUInt8 DEF_pipeline_toMP_ctps_4_infifo_first__350_BIT_63__ETC___d1354;
  tUInt8 DEF_pipeline_toMP_ctps_3_infifo_first__237_BIT_63__ETC___d1241;
  tUInt8 DEF_pipeline_toMP_ctps_2_infifo_first__124_BIT_63__ETC___d1128;
  tUInt8 DEF_pipeline_toMP_ctps_1_infifo_first__011_BIT_63__ETC___d1015;
  tUInt8 DEF_pipeline_toMP_ctps_0_infifo_first__97_BIT_63_9_ETC___d901;
  tUInt8 DEF_pipeline_fft_fft_counter_08_EQ_0___d112;
  tUInt32 DEF__theResult___fst_f__h168050;
  tUInt32 DEF__theResult___fst_i__h168049;
  tUInt32 DEF__theResult___snd_fst_f__h168018;
  tUInt32 DEF__theResult___snd_fst_i__h168017;
  tUInt32 DEF__theResult___fst_f__h162858;
  tUInt32 DEF__theResult___fst_i__h162857;
  tUInt32 DEF__theResult___snd_fst_f__h162826;
  tUInt32 DEF__theResult___snd_fst_i__h162825;
  tUInt32 DEF__theResult___fst_f__h157666;
  tUInt32 DEF__theResult___fst_i__h157665;
  tUInt32 DEF__theResult___snd_fst_f__h157634;
  tUInt32 DEF__theResult___snd_fst_i__h157633;
  tUInt32 DEF__theResult___fst_f__h152474;
  tUInt32 DEF__theResult___fst_i__h152473;
  tUInt32 DEF__theResult___snd_fst_f__h152442;
  tUInt32 DEF__theResult___snd_fst_i__h152441;
  tUInt32 DEF__theResult___fst_f__h147282;
  tUInt32 DEF__theResult___fst_i__h147281;
  tUInt32 DEF__theResult___snd_fst_f__h147250;
  tUInt32 DEF__theResult___snd_fst_i__h147249;
  tUInt32 DEF__theResult___fst_f__h142090;
  tUInt32 DEF__theResult___fst_i__h142089;
  tUInt32 DEF__theResult___snd_fst_f__h142058;
  tUInt32 DEF__theResult___snd_fst_i__h142057;
  tUInt32 DEF__theResult___fst_f__h136898;
  tUInt32 DEF__theResult___fst_i__h136897;
  tUInt32 DEF__theResult___snd_fst_f__h136866;
  tUInt32 DEF__theResult___snd_fst_i__h136865;
  tUInt32 DEF__theResult___fst_f__h131649;
  tUInt32 DEF__theResult___fst_i__h131648;
  tUInt32 DEF__theResult___snd_fst_f__h131617;
  tUInt32 DEF__theResult___snd_fst_i__h131616;
  tUInt8 DEF_pipeline_ifft_fft_fft_counter_633_EQ_2___d2641;
  tUInt8 DEF_pipeline_fft_fft_counter_08_EQ_2___d116;
  tUInt8 DEF_IF_pipeline_toMP_ctps_7_infifo_first__689_BIT__ETC___d1721;
  tUInt8 DEF_IF_pipeline_toMP_ctps_7_infifo_first__689_BIT__ETC___d1716;
  tUInt8 DEF_IF_pipeline_toMP_ctps_7_infifo_first__689_BIT__ETC___d1708;
  tUInt8 DEF_IF_pipeline_toMP_ctps_7_infifo_first__689_BIT__ETC___d1701;
  tUInt8 DEF_IF_pipeline_toMP_ctps_6_infifo_first__576_BIT__ETC___d1608;
  tUInt8 DEF_IF_pipeline_toMP_ctps_6_infifo_first__576_BIT__ETC___d1603;
  tUInt8 DEF_IF_pipeline_toMP_ctps_6_infifo_first__576_BIT__ETC___d1595;
  tUInt8 DEF_IF_pipeline_toMP_ctps_6_infifo_first__576_BIT__ETC___d1588;
  tUInt8 DEF_IF_pipeline_toMP_ctps_5_infifo_first__463_BIT__ETC___d1495;
  tUInt8 DEF_IF_pipeline_toMP_ctps_5_infifo_first__463_BIT__ETC___d1490;
  tUInt8 DEF_IF_pipeline_toMP_ctps_5_infifo_first__463_BIT__ETC___d1482;
  tUInt8 DEF_IF_pipeline_toMP_ctps_5_infifo_first__463_BIT__ETC___d1475;
  tUInt8 DEF_IF_pipeline_toMP_ctps_4_infifo_first__350_BIT__ETC___d1382;
  tUInt8 DEF_IF_pipeline_toMP_ctps_4_infifo_first__350_BIT__ETC___d1377;
  tUInt8 DEF_IF_pipeline_toMP_ctps_4_infifo_first__350_BIT__ETC___d1369;
  tUInt8 DEF_IF_pipeline_toMP_ctps_4_infifo_first__350_BIT__ETC___d1362;
  tUInt8 DEF_IF_pipeline_toMP_ctps_3_infifo_first__237_BIT__ETC___d1269;
  tUInt8 DEF_IF_pipeline_toMP_ctps_3_infifo_first__237_BIT__ETC___d1264;
  tUInt8 DEF_IF_pipeline_toMP_ctps_3_infifo_first__237_BIT__ETC___d1256;
  tUInt8 DEF_IF_pipeline_toMP_ctps_3_infifo_first__237_BIT__ETC___d1249;
  tUInt8 DEF_IF_pipeline_toMP_ctps_2_infifo_first__124_BIT__ETC___d1156;
  tUInt8 DEF_IF_pipeline_toMP_ctps_2_infifo_first__124_BIT__ETC___d1151;
  tUInt8 DEF_IF_pipeline_toMP_ctps_2_infifo_first__124_BIT__ETC___d1143;
  tUInt8 DEF_IF_pipeline_toMP_ctps_2_infifo_first__124_BIT__ETC___d1136;
  tUInt8 DEF_IF_pipeline_toMP_ctps_1_infifo_first__011_BIT__ETC___d1043;
  tUInt8 DEF_IF_pipeline_toMP_ctps_1_infifo_first__011_BIT__ETC___d1038;
  tUInt8 DEF_IF_pipeline_toMP_ctps_1_infifo_first__011_BIT__ETC___d1030;
  tUInt8 DEF_IF_pipeline_toMP_ctps_1_infifo_first__011_BIT__ETC___d1023;
  tUInt8 DEF_IF_pipeline_toMP_ctps_0_infifo_first__97_BIT_6_ETC___d929;
  tUInt8 DEF_IF_pipeline_toMP_ctps_0_infifo_first__97_BIT_6_ETC___d924;
  tUInt8 DEF_IF_pipeline_toMP_ctps_0_infifo_first__97_BIT_6_ETC___d916;
  tUInt8 DEF_IF_pipeline_toMP_ctps_0_infifo_first__97_BIT_6_ETC___d909;
  tUInt8 DEF_pipeline_fromMP_ptcs_7_iter_552_EQ_15___d2553;
  tUInt8 DEF_pipeline_fromMP_ptcs_6_iter_472_EQ_15___d2473;
  tUInt8 DEF_pipeline_fromMP_ptcs_5_iter_392_EQ_15___d2393;
  tUInt8 DEF_pipeline_fromMP_ptcs_4_iter_312_EQ_15___d2313;
  tUInt8 DEF_pipeline_fromMP_ptcs_3_iter_232_EQ_15___d2233;
  tUInt8 DEF_pipeline_fromMP_ptcs_2_iter_152_EQ_15___d2153;
  tUInt8 DEF_pipeline_fromMP_ptcs_1_iter_072_EQ_15___d2073;
  tUInt8 DEF_pipeline_fromMP_ptcs_0_iter_992_EQ_15___d1993;
  tUInt8 DEF_pipeline_toMP_ctps_7_iter_739_EQ_15___d1740;
  tUInt8 DEF_pipeline_toMP_ctps_6_iter_626_EQ_15___d1627;
  tUInt8 DEF_pipeline_toMP_ctps_5_iter_513_EQ_15___d1514;
  tUInt8 DEF_pipeline_toMP_ctps_4_iter_400_EQ_15___d1401;
  tUInt8 DEF_pipeline_toMP_ctps_3_iter_287_EQ_15___d1288;
  tUInt8 DEF_pipeline_toMP_ctps_2_iter_174_EQ_15___d1175;
  tUInt8 DEF_pipeline_toMP_ctps_1_iter_061_EQ_15___d1062;
  tUInt8 DEF_pipeline_toMP_ctps_0_iter_47_EQ_15___d948;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_7_iter_552_EQ_15_553___d2554;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_6_iter_472_EQ_15_473___d2474;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_5_iter_392_EQ_15_393___d2394;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_4_iter_312_EQ_15_313___d2314;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_3_iter_232_EQ_15_233___d2234;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_2_iter_152_EQ_15_153___d2154;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_1_iter_072_EQ_15_073___d2074;
  tUInt8 DEF_NOT_pipeline_fromMP_ptcs_0_iter_992_EQ_15_993___d1994;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_7_iter_739_EQ_15_740___d1741;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_7_infifo_first__689__ETC___d1724;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_6_iter_626_EQ_15_627___d1628;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_6_infifo_first__576__ETC___d1611;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_5_iter_513_EQ_15_514___d1515;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_5_infifo_first__463__ETC___d1498;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_4_iter_400_EQ_15_401___d1402;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_4_infifo_first__350__ETC___d1385;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_3_iter_287_EQ_15_288___d1289;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_3_infifo_first__237__ETC___d1272;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_2_iter_174_EQ_15_175___d1176;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_2_infifo_first__124__ETC___d1159;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_1_iter_061_EQ_15_062___d1063;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_1_infifo_first__011__ETC___d1046;
  tUInt8 DEF_NOT_pipeline_toMP_ctps_0_iter_47_EQ_15_48___d949;
  tUInt8 DEF_NOT_IF_pipeline_toMP_ctps_0_infifo_first__97_B_ETC___d932;
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h369177;
  tUInt32 DEF_x__h369335;
  tUInt32 DEF_TASK_fopen___d3611;
  tUInt32 DEF_TASK_fopen___d3609;
  tUWide DEF_pipeline_ifft_outfifo_first____d3584;
  tUWide DEF_pipeline_ifft_fft_fft_stage_reg__h230877;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first____d3420;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first____d2646;
  tUWide DEF_pipeline_fromMP_outFifo_first____d3568;
  tUWide DEF_pipeline_toMP_inFifo_first____d1818;
  tUWide DEF_pipeline_fft_fft_stage_reg__h13866;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first____d3553;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first____d121;
  tUWide DEF_pipeline_fromMP_inFifo_first____d2594;
  tUWide DEF_pipeline_pitchAdjust_outFifo_first____d3561;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first____d1861;
  tUWide DEF_pipeline_toMP_outFifo_first____d3557;
  tUWide DEF_pipeline_pitchAdjust_magFifo_first____d1891;
  tUWide DEF_pipeline_overlayer_infifo_first____d3463;
  tUWide DEF_pipeline_overlayer_window__h353442;
  tUWide DEF_pipeline_pitchAdjust_dphaseFifo_first____d1893;
  tUWide DEF_pipeline_overSampler_outfifo_first____d3526;
  tUWide DEF_pipeline_overSampler_window__h10420;
  tUInt32 DEF_m_out___d3640;
  tUWide DEF_pipeline_overSampler_window_04_BITS_127_TO_32___d105;
  tUInt8 DEF_x__h229406;
  tUInt8 DEF_x__h12377;
  tUWide DEF_pipeline_fromMP_outFifo_first__568_BITS_511_TO_ETC___d3580;
  tUWide DEF_pipeline_fromMP_outFifo_first__568_BITS_511_TO_ETC___d3577;
  tUWide DEF_pipeline_overSampler_outfifo_first__526_BITS_1_ETC___d3546;
  tUWide DEF_pipeline_overSampler_outfifo_first__526_BITS_1_ETC___d3541;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__420_BI_ETC___d3459;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__420_BI_ETC___d3449;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_633_EQ_0_637__ETC___d3412;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_633_EQ_0_637__ETC___d3406;
  tUWide DEF_IF_pipeline_fft_fft_counter_08_EQ_0_12_THEN_pi_ETC___d894;
  tUWide DEF_IF_pipeline_fft_fft_counter_08_EQ_0_12_THEN_pi_ETC___d888;
  tUWide DEF_pipeline_fromMP_ptcs_7_outfifo_first__620_CONC_ETC___d2631;
  tUWide DEF_pipeline_fromMP_ptcs_7_outfifo_first__620_CONC_ETC___d2628;
  tUWide DEF_pipeline_toMP_ctps_7_outfifo_first__844_CONCAT_ETC___d1855;
  tUWide DEF_pipeline_toMP_ctps_7_outfifo_first__844_CONCAT_ETC___d1852;
  tUWide DEF__0_CONCAT_pipeline_pitchAdjust_magFifo_first__8_ETC___d1936;
  tUWide DEF__0_CONCAT_pipeline_pitchAdjust_magFifo_first__8_ETC___d1925;
  tUWide DEF_pipeline_fromMP_outFifo_first__568_BITS_511_TO_ETC___d3574;
  tUWide DEF_pipeline_overSampler_outfifo_first__526_BITS_1_ETC___d3536;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__420_BI_ETC___d3439;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_633_EQ_0_637__ETC___d3400;
  tUWide DEF_IF_pipeline_fft_fft_counter_08_EQ_0_12_THEN_pi_ETC___d882;
  tUWide DEF_pipeline_fromMP_ptcs_7_outfifo_first__620_CONC_ETC___d2625;
  tUWide DEF_pipeline_toMP_ctps_7_outfifo_first__844_CONCAT_ETC___d1849;
  tUWide DEF__0_CONCAT_pipeline_pitchAdjust_magFifo_first__8_ETC___d1914;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first__861_BITS_38_ETC___d1873;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first__861_BITS_38_ETC___d1870;
  tUWide DEF_pipeline_fromMP_outFifo_first__568_BITS_511_TO_ETC___d3571;
  tUWide DEF_pipeline_overSampler_outfifo_first__526_BITS_1_ETC___d3531;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__420_BI_ETC___d3429;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_633_EQ_0_637__ETC___d3025;
  tUWide DEF_IF_pipeline_fft_fft_counter_08_EQ_0_12_THEN_pi_ETC___d504;
  tUWide DEF_pipeline_fromMP_ptcs_7_outfifo_first__620_CONC_ETC___d2622;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first__861_BITS_38_ETC___d1867;
  tUWide DEF_pipeline_toMP_ctps_7_outfifo_first__844_CONCAT_ETC___d1846;
  tUWide DEF__0_CONCAT_pipeline_pitchAdjust_magFifo_first__8_ETC___d1903;
  tUWide DEF_pipeline_ifft_outfifo_first__584_BITS_511_TO_4_ETC___d3596;
  tUWide DEF_pipeline_ifft_outfifo_first__584_BITS_511_TO_4_ETC___d3593;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first__861_BITS_35_ETC___d1885;
  tUWide DEF_pipeline_pitchAdjust_inFifo_first__861_BITS_35_ETC___d1882;
  tUWide DEF_pipeline_overlayer_infifo_first__463_BITS_127__ETC___d3496;
  tUWide DEF_pipeline_overlayer_infifo_first__463_BITS_127__ETC___d3487;
  tUWide DEF_pipeline_overSampler_infifo_first__03_CONCAT_p_ETC___d106;
 
 /* Rules */
 public:
  void RL_pipeline_fir_process0();
  void RL_pipeline_fir_process1();
  void RL_pipeline_chunker_iterate();
  void RL_pipeline_overSampler_shiftin();
  void RL_pipeline_fft_fft_stage_count();
  void RL_pipeline_fft_fft_circular_fft();
  void RL_pipeline_toMP_ctps_0_start();
  void RL_pipeline_toMP_ctps_0_iterate();
  void RL_pipeline_toMP_ctps_1_start();
  void RL_pipeline_toMP_ctps_1_iterate();
  void RL_pipeline_toMP_ctps_2_start();
  void RL_pipeline_toMP_ctps_2_iterate();
  void RL_pipeline_toMP_ctps_3_start();
  void RL_pipeline_toMP_ctps_3_iterate();
  void RL_pipeline_toMP_ctps_4_start();
  void RL_pipeline_toMP_ctps_4_iterate();
  void RL_pipeline_toMP_ctps_5_start();
  void RL_pipeline_toMP_ctps_5_iterate();
  void RL_pipeline_toMP_ctps_6_start();
  void RL_pipeline_toMP_ctps_6_iterate();
  void RL_pipeline_toMP_ctps_7_start();
  void RL_pipeline_toMP_ctps_7_iterate();
  void RL_pipeline_toMP_puts();
  void RL_pipeline_toMP_gets();
  void RL_pipeline_pitchAdjust_dphase_calculate();
  void RL_pipeline_pitchAdjust_result_index_calculate();
  void RL_pipeline_fromMP_ptcs_0_start();
  void RL_pipeline_fromMP_ptcs_0_iterate();
  void RL_pipeline_fromMP_ptcs_1_start();
  void RL_pipeline_fromMP_ptcs_1_iterate();
  void RL_pipeline_fromMP_ptcs_2_start();
  void RL_pipeline_fromMP_ptcs_2_iterate();
  void RL_pipeline_fromMP_ptcs_3_start();
  void RL_pipeline_fromMP_ptcs_3_iterate();
  void RL_pipeline_fromMP_ptcs_4_start();
  void RL_pipeline_fromMP_ptcs_4_iterate();
  void RL_pipeline_fromMP_ptcs_5_start();
  void RL_pipeline_fromMP_ptcs_5_iterate();
  void RL_pipeline_fromMP_ptcs_6_start();
  void RL_pipeline_fromMP_ptcs_6_iterate();
  void RL_pipeline_fromMP_ptcs_7_start();
  void RL_pipeline_fromMP_ptcs_7_iterate();
  void RL_pipeline_fromMP_puts();
  void RL_pipeline_fromMP_gets();
  void RL_pipeline_ifft_fft_fft_stage_count();
  void RL_pipeline_ifft_fft_fft_circular_fft();
  void RL_pipeline_ifft_inversify();
  void RL_pipeline_overlayer_shiftout();
  void RL_pipeline_splitter_iterate();
  void RL_pipeline_fir_to_chunker();
  void RL_pipeline_chunker_to_oversampler();
  void RL_pipeline_oversampler_to_fft();
  void RL_pipeline_fft_to_toMP();
  void RL_pipeline_toMP_to_pitchAdjust();
  void RL_pipeline_pitchAdjust_to_fromMP();
  void RL_pipeline_fromMP_to_ifft();
  void RL_pipeline_ifft_to_overlayer();
  void RL_pipeline_overlayer_to_splitter();
  void RL_init();
  void RL_read();
  void RL_pad();
  void RL_write();
  void RL_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
};

#endif /* ifndef __mkTestDriver_h__ */
