/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Sat Jul 15 06:09:48 CST 2023
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTestDriver_h__
#define __mkTestDriver_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMultiplier.h"


/* Class declaration for the mkTestDriver module */
class MOD_mkTestDriver : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_doneread;
  MOD_Reg<tUInt8> INST_m_doneread_double_write_error;
  MOD_Reg<tUInt32> INST_m_in;
  MOD_Reg<tUInt8> INST_m_in_double_write_error;
  MOD_Reg<tUInt8> INST_m_inited;
  MOD_Reg<tUInt8> INST_m_inited_double_write_error;
  MOD_Reg<tUInt32> INST_m_out;
  MOD_Reg<tUInt8> INST_m_out_double_write_error;
  MOD_Counter<tUInt32> INST_m_outstanding;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index_double_write_error;
  MOD_Fifo<tUInt64> INST_pipeline_chunker_infifo;
  MOD_Fifo<tUWide> INST_pipeline_chunker_outfifo;
  MOD_Reg<tUWide> INST_pipeline_chunker_pending;
  MOD_Reg<tUInt8> INST_pipeline_chunker_pending_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_counter;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_counter_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_pipeline_fft_fft_stage_reg;
  MOD_Reg<tUInt8> INST_pipeline_fft_fft_stage_reg_double_write_error;
  MOD_Fifo<tUInt32> INST_pipeline_fir_infifo;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_0;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_1;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_2;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_3;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_4;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_5;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_6;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_7;
  MOD_mkMultiplier INST_pipeline_fir_multiplier_8;
  MOD_Fifo<tUInt32> INST_pipeline_fir_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_0;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_0_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_1;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_1_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_2;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_2_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_3;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_3_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_4;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_4_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_5;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_5_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_6;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_6_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_7;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_7_double_write_error;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_counter;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_counter_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_outputFIFO;
  MOD_Reg<tUWide> INST_pipeline_ifft_fft_fft_stage_reg;
  MOD_Reg<tUInt8> INST_pipeline_ifft_fft_fft_stage_reg_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_outfifo;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_splitter_infifo;
  MOD_Fifo<tUInt64> INST_pipeline_splitter_outfifo;
 
 /* Constructor */
 public:
  MOD_mkTestDriver(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_finish;
  tUInt8 DEF_CAN_FIRE_RL_finish;
  tUInt8 DEF_WILL_FIRE_RL_write;
  tUInt8 DEF_CAN_FIRE_RL_write;
  tUInt8 DEF_WILL_FIRE_RL_pad;
  tUInt8 DEF_CAN_FIRE_RL_pad;
  tUInt8 DEF_WILL_FIRE_RL_read;
  tUInt8 DEF_CAN_FIRE_RL_read;
  tUInt8 DEF_WILL_FIRE_RL_init;
  tUInt8 DEF_CAN_FIRE_RL_init;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_circular_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_circular_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_stage_count;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_stage_count;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_circular_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_circular_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_stage_count;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_stage_count;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_process1;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_process1;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_process0;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_process0;
  tUInt8 DEF_x__h132416;
  tUInt8 DEF_x__h12942;
  tUInt8 DEF_x__h7384;
  tUInt8 DEF_pipeline_chunker_index_4_EQ_7___d85;
  tUInt8 DEF_pipeline_ifft_fft_fft_counter_13_EQ_0___d917;
  tUInt8 DEF_pipeline_fft_fft_counter_24_EQ_0___d128;
  tUInt8 DEF_pipeline_ifft_fft_fft_counter_13_EQ_2___d921;
  tUInt8 DEF_pipeline_fft_fft_counter_24_EQ_2___d132;
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h260743;
  tUInt32 DEF_x__h260901;
  tUInt32 DEF_TASK_fopen___d1851;
  tUInt32 DEF_TASK_fopen___d1849;
  tUWide DEF_pipeline_splitter_infifo_first____d1745;
  tUWide DEF_pipeline_ifft_outfifo_first____d1840;
  tUWide DEF_pipeline_ifft_fft_fft_stage_reg__h131433;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first____d1700;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first____d926;
  tUWide DEF_pipeline_fft_fft_stage_reg__h11939;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first____d1824;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first____d137;
  tUWide DEF_pipeline_chunker_pending__h8308;
  tUWide DEF_pipeline_chunker_outfifo_first____d1802;
  tUInt32 DEF_m_out___d1880;
  tUInt8 DEF_x__h129962;
  tUInt8 DEF_x__h10450;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__824_BITS_51_ETC___d1836;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__824_BITS_51_ETC___d1833;
  tUWide DEF_pipeline_chunker_outfifo_first__802_BITS_511_T_ETC___d1814;
  tUWide DEF_pipeline_chunker_outfifo_first__802_BITS_511_T_ETC___d1811;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__700_BI_ETC___d1739;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__700_BI_ETC___d1729;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_13_EQ_0_17_TH_ETC___d1692;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_13_EQ_0_17_TH_ETC___d1686;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d121;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d114;
  tUWide DEF_IF_pipeline_fft_fft_counter_24_EQ_0_28_THEN_pi_ETC___d910;
  tUWide DEF_IF_pipeline_fft_fft_counter_24_EQ_0_28_THEN_pi_ETC___d904;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__824_BITS_51_ETC___d1830;
  tUWide DEF_pipeline_chunker_outfifo_first__802_BITS_511_T_ETC___d1808;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__700_BI_ETC___d1719;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_13_EQ_0_17_TH_ETC___d1680;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d107;
  tUWide DEF_IF_pipeline_fft_fft_counter_24_EQ_0_28_THEN_pi_ETC___d898;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__824_BITS_51_ETC___d1827;
  tUWide DEF_pipeline_chunker_outfifo_first__802_BITS_511_T_ETC___d1805;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__700_BI_ETC___d1709;
  tUWide DEF_IF_pipeline_ifft_fft_fft_counter_13_EQ_0_17_TH_ETC___d1305;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d100;
  tUWide DEF_IF_pipeline_fft_fft_counter_24_EQ_0_28_THEN_pi_ETC___d520;
 
 /* Rules */
 public:
  void RL_pipeline_fir_process0();
  void RL_pipeline_fir_process1();
  void RL_pipeline_chunker_iterate();
  void RL_pipeline_fft_fft_stage_count();
  void RL_pipeline_fft_fft_circular_fft();
  void RL_pipeline_ifft_fft_fft_stage_count();
  void RL_pipeline_ifft_fft_fft_circular_fft();
  void RL_pipeline_ifft_inversify();
  void RL_pipeline_splitter_iterate();
  void RL_pipeline_fir_to_chunker();
  void RL_pipeline_chunker_to_fft();
  void RL_pipeline_fft_to_ifft();
  void RL_pipeline_ifft_to_splitter();
  void RL_init();
  void RL_read();
  void RL_pad();
  void RL_write();
  void RL_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
};

#endif /* ifndef __mkTestDriver_h__ */
